# Generated by Django 4.2.6 on 2023-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('movieID', models.IntegerField()),
                ('releaseDate', models.DateField()),
                ('rating', models.FloatField()),
                ('imageURL', models.URLField(blank=True, null=True)),
                ('posterURL', models.URLField(blank=True, null=True)),
                ('overview', models.TextField()),
                ('trailer_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
